name: image_manipulation_app
description: A Flutter app for image editing via a Flask backend.

publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  image_picker: ^1.1.0
  permission_handler: ^12.0.1
  path_provider: ^2.1.3
  image_gallery_saver_plus: ^4.0.1
  image: ^4.0.17
  shared_preferences: ^2.1.1
  device_info_plus: ^12.1.0
  camera: ^0.11.0+1
  tflite_flutter: 0.11.0
  flutter_image_compress: ^2.3.0
  path: ^1.8.3
  crypto: ^3.0.2
  google_mlkit_face_detection: ^0.13.1
  google_mlkit_commons: ^0.11.0
  flutter_3d_viewer: ^1.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets:
  # - assets/images/
